# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gRPC.CloudRoute_pb2 as CloudRoute__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in CloudRoute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


# Client will use this class
class CloudRouteStub(object):
    """CloudRoute service provides both unary and streaming RPC methods
    for sending frames from the Raspberry Pi to the cloud model and
    receiving detection results (bounding boxes, classes, confidence).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CloudRoute = channel.unary_unary(
                '/CloudRoute/CloudRoute',
                request_serializer=CloudRoute__pb2.DetectionRequest.SerializeToString,
                response_deserializer=CloudRoute__pb2.DetectionResult.FromString,
                _registered_method=True)
        self.CloudRouteStream = channel.stream_stream(
                '/CloudRoute/CloudRouteStream',
                request_serializer=CloudRoute__pb2.DetectionRequest.SerializeToString,
                response_deserializer=CloudRoute__pb2.DetectionResult.FromString,
                _registered_method=True)


# Server will use this class
class CloudRouteServicer(object):
    """CloudRoute service provides both unary and streaming RPC methods
    for sending frames from the Raspberry Pi to the cloud model and
    receiving detection results (bounding boxes, classes, confidence).
    """

    def CloudRoute(self, request, context):
        """Unary RPC:
        Sends a single frame and returns a single detection result.
        Useful for testing, debugging, or low-frequency inference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloudRouteStream(self, request_iterator, context):
        """Bidirectional Streaming RPC:
        Allows the Pi to continuously stream frames to the cloud,
        while the cloud streams back detection results in real time.
        This is the main method used by the GuardCar pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudRouteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CloudRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CloudRoute,
                    request_deserializer=CloudRoute__pb2.DetectionRequest.FromString,
                    response_serializer=CloudRoute__pb2.DetectionResult.SerializeToString,
            ),
            'CloudRouteStream': grpc.stream_stream_rpc_method_handler(
                    servicer.CloudRouteStream,
                    request_deserializer=CloudRoute__pb2.DetectionRequest.FromString,
                    response_serializer=CloudRoute__pb2.DetectionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CloudRoute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CloudRoute', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudRoute(object):
    """CloudRoute service provides both unary and streaming RPC methods
    for sending frames from the Raspberry Pi to the cloud model and
    receiving detection results (bounding boxes, classes, confidence).
    """

    @staticmethod
    def CloudRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CloudRoute/CloudRoute',
            CloudRoute__pb2.DetectionRequest.SerializeToString,
            CloudRoute__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloudRouteStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/CloudRoute/CloudRouteStream',
            CloudRoute__pb2.DetectionRequest.SerializeToString,
            CloudRoute__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
