# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CloudRoute.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CloudRoute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43loudRoute.proto\"R\n\x10\x44\x65tectionRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\x05\"C\n\x0f\x44\x65tectionResult\x12\x1e\n\ndetections\x18\x01 \x03(\x0b\x32\n.Detection\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x05\"u\n\tDetection\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\n\n\x02x1\x18\x04 \x01(\x02\x12\n\n\x02y1\x18\x05 \x01(\x02\x12\n\n\x02x2\x18\x06 \x01(\x02\x12\n\n\x02y2\x18\x07 \x01(\x02\x32|\n\nCloudRoute\x12\x31\n\nCloudRoute\x12\x11.DetectionRequest\x1a\x10.DetectionResult\x12;\n\x10\x43loudRouteStream\x12\x11.DetectionRequest\x1a\x10.DetectionResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CloudRoute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONREQUEST']._serialized_start=20
  _globals['_DETECTIONREQUEST']._serialized_end=102
  _globals['_DETECTIONRESULT']._serialized_start=104
  _globals['_DETECTIONRESULT']._serialized_end=171
  _globals['_DETECTION']._serialized_start=173
  _globals['_DETECTION']._serialized_end=290
  _globals['_CLOUDROUTE']._serialized_start=292
  _globals['_CLOUDROUTE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
